TokTok/hs-toxcore-c

.travis.yml
src/Network/Tox/C/Callbacks.hs
src/Network/Tox/C/Options.hs
src/Network/Tox/C/Tox.hs
src/Network/Tox/C/Type.hs
test/Network/Tox/C/ToxSpec.hs
tools/groupbot.hs
toxcore.cabal

Also, add "groupbot" binary that isn't a group bot, yet. In the future,
it may grow into that.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-toxcore-c/2)

Remove saltine dependency in toxcore.

---

.gitignore
toxcore.cabal

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-toxcore-c/3)

Add missing toxcore extra-libraries dependency.

---

src/Network/Tox/C/Callbacks.hs
src/Network/Tox/C/Tox.hs
tools/groupbot.hs
toxcore.cabal

I wrapped most of callbacks and API calls in haskell-friendly functions.
What's missing:
- AV part
- Tox log
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-toxcore-c/5)

Tox FFI API improved

---

tools/groupbot.hs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-toxcore-c/7)

Minor style cleanups in groupbot.

---

.travis.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-toxcore-c/10)

Don't build toxav for hs-toxcore-c.

---

src/Network/Tox/C/Tox.hs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-toxcore-c/11)

Format code according to new stylish-haskell.

---

BUILD

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-toxcore-c/12)

Add bazel config for hs-toxcore-c.

---

.gitignore

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-toxcore-c/13)

Ignore generated stub header.

---

.travis.yml
README.md
src/Network/Tox/C/Callbacks.hs
src/Network/Tox/C/Tox.hs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-toxcore-c/20)

Adopt new conference peer nick/list_changed callbacks.

---

BUILD.bazel
src/Network/Tox/C/Options.hs
test/Network/Tox/C/ToxSpec.hs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-toxcore-c/21)

Add testsuite to bazel build.

---

toxcore.cabal

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-toxcore-c/22)

Prepare for hs-toxcore-c version 0.2.0 release.

---

.travis.yml
src/Network/Tox/C/Callbacks.hs
src/Network/Tox/C/Tox.hs
stack.yaml
tools/groupbot/Main.hs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-toxcore-c/27)

Build with `stack` instead of `cabal` on Travis.

---

BUILD.bazel
test/Network/Tox/C/ToxSpec.hs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-toxcore-c/28)

Update to new way of specifying dependencies on base packages.

---

stack.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-toxcore-c/31)

Format yaml files according to yamllint's requirements.

---

BUILD.bazel
test/Network/Tox/CSpec.hs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-toxcore-c/32)

Use new hspec_test rule to work around rules_haskell issue 625.

---

BUILD.bazel
test/Network/Tox/CSpec.hs

nurupo's node is down.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-toxcore-c/33)

Use a new bootstrap node for testing.

---

BUILD.bazel

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-toxcore-c/34)

Use new rules_haskell name for bazel 2.1.1.

---

.travis.yml
BUILD.bazel
toxcore-c.cabal

Also: install libsodium from apt instead of from source.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-toxcore-c/37)

Rename package to "toxcore-c".

---

toxcore-c.cabal

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-toxcore-c/40)

Avoid unicode characters in .cabal files.

---

BUILD.bazel

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-toxcore-c/41)

Remove standard_travis flag, as it is becoming default.

---

.cirrus.yml
BUILD.bazel
test/Data/ByteString/Arbitrary.hs
test/Network/Tox/C/ToxSpec.hs
test/Network/Tox/CSpec.hs
tools/groupbot.hs
toxcore-c.cabal

We don't officially support any older version anymore, though it might work.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-toxcore-c/46)

chore: Upgrade to ghc-8.10.3

---

.cirrus.yml
.github/settings.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-toxcore-c/49)

chore: Upgrade to latest toktok-stack

---

.cirrus.yml
stack.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-toxcore-c/50)

chore: Use latest instead of versioned toktok-stack image.

---

.github/docker/Dockerfile
.github/workflows/checks.yml
.github/workflows/ci.yml
.github/workflows/publish.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-toxcore-c/51)

chore: Add toktok standard haskell CI builds.

---

.github/docker/Dockerfile
BUILD.bazel
test/Network/Tox/CSpec.hs
tools/groupbot.hs
toxcore-c.cabal

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-toxcore-c/52)

chore: Use toktok-stack image for haskell stack builds.

---

tools/prepare_third_party.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-toxcore-c/56)

chore: Install toxcore before building haddock documentation.

---

tools/prepare_third_party.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-toxcore-c/57)

chore: Add missing msgpack dependency.

---

src/Network/Tox/C/Events.hs

So Safe modules can import it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-toxcore-c/58)

chore: Mark Events module as Trustworthy.

---

toxcore-c.cabal

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-toxcore-c/60)

chore: Update the test sources in .cabal file.

---

.github/settings.yml
.github/workflows/ci.yml
BUILD.bazel
stack.yaml
test/Network/Tox/C/EventsSpec.hs
toxcore-c.cabal

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-toxcore-c/64)

chore: Update to msgpack-types 0.3.

---

test/Network/Tox/C/EventsSpec.hs

This is too flaky right now.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-toxcore-c/66)

test: Don't fail tests when bootstrap fails.

---

test/Network/Tox/Types/EventsSpec.hs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-toxcore-c/68)

test: Use ipv4 localhost for bootstrap.

---

src/Network/Tox/C/CEnum.hs
src/Network/Tox/C/Constants.hs
src/Network/Tox/C/Options.hs
src/Network/Tox/C/Tox.hs
src/Network/Tox/C/Type.hs
src/Network/Tox/C/Version.hs
src/Network/Tox/Types/Events.hs
stack.yaml
test/Network/Tox/C/ToxSpec.hs
tools/groupbot.hs
toxcore-c.cabal

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/hs-toxcore-c/69)

chore: Upgrade stack LTS snapshot to 21.9 (GHC 9.4.6).

---

.cirrus.yml
BUILD.bazel
test/Network/Tox/Types/EventsSpec.hs
tools/BUILD.bazel

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/hs-toxcore-c/72)

chore: Update to new third_party method for haskell deps.

---

BUILD.bazel
tools/BUILD.bazel

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/hs-toxcore-c/74)

cleanup: Use apigen to generate the FFI code.

---

src/Network/Tox/Types/Events.hs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/hs-toxcore-c/80)

feat: Add support for group and DHT debug events.

---

tools/groupbot.hs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/hs-toxcore-c/81)

feat: Echo messages to groupbot in conferences.

---

tools/prepare_third_party.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/hs-toxcore-c/82)

fix: Clone submodules when checking out toxcore.

---

src/FFI/Tox/Tox.hs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/hs-toxcore-c/84)

cleanup: Remove `Tox_System` stuff for now.

---

BUILD.bazel
test/Network/Tox/C/ToxSpec.hs
toxcore-c.cabal

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/hs-toxcore-c/86)

test: Remove static numbers in tox constants tests.

---

.github/workflows/draft.yml
.reviewable/completion.js
.reviewable/settings.yaml
BUILD.bazel
toxcore-c.cabal

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/hs-toxcore-c/88)

chore: Add reviewable config; rename release workflow to draft.

---

tools/prepare_third_party.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/hs-toxcore-c/89)

chore: Use ninja for toxcore build.
